### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by huytuong010101** [HighwayWu/Tianchi-FFT2#4]
Hi bro, 
This competition finished, so I can't access the dataset. Can you public the dataset with me?
Thank you so much,

**Comment by HighwayWu** [comment]
Sorry that I can't re-distribute the dataset according to the license.
BTW, the long-term race is open, and you may download the dataset from the official website: https://tianchi.aliyun.com/competition/entrance/531812/information.

**Comment by HighwayWu** [comment]
FYI: The dataset link is now updated.

**Comment by huytuong010101** [comment]
> FYI: The dataset link is now updated.

thank you so much <3
