### ISSUE TITLE
【数据处理】想请教一下，是怎么进行数据预处理的

### ISSUE THREAD

**Issue by ZzyChris97** [HighwayWu/Tianchi-FFT2#5]
我从readme中的链接下载到的数据没法直接运行，想请问下是怎么做数据处理的，那些npy文件是什么作用和格式

**Comment by HighwayWu** [comment]
建议按照个人习惯进行数据处理即可。本项目中是将文件的绝对路径写入npy文件中，例如[[img.png mask.png], [img2.png mask2.png], ...]。
